apiVersion: v1
kind: Service
metadata:
  name:  voting-app-service
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    {{- with .Values.votingapp.service.labels }}
    {{ toYaml . }}
    {{- end }}
spec:
  type:  ClusterIP
  selector:
    name: voting-app-pod
    type: frontend
  ports:
  {{- with .Values.votingapp.service.ports }}
  {{ toYaml . | nindent 4 }}
  {{- end }}